language: python
cache: pip
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.dev.txt"
# command to run tests
before_script:
  - source .env
script:
  - python server/tests/test_demos_service.py
  - python server/tests/test_users_service.py