language: python
cache: pip
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.dev.txt"
# command to run tests
before_script:
  - rm .env.local
  - source .env
script:
  - python server/tests/run_tests.py